# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - ChatApi1

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read #This is required for actions/checkout

    env:
      SOLUTION_FILE: ChatApi/ChatAPI.sln                  # <--- ajuste se não estiver na raiz
      API_PROJECT: ChatApi/ChatAPI/ChatAPI.csproj         # <--- caminho do .csproj da Web API
      PUBLISH_DIR: ${{ github.workspace }}\publish

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      # - name: Debug layout
      #   run: |
      #     pwd
      #     dir /a

      - name: Restore
        run: dotnet restore "${{ env.SOLUTION_FILE }}"

      - name: Build (Release)
        run: dotnet build "${{ env.SOLUTION_FILE }}" --no-restore -c Release

      - name: Publish Web API
        run: dotnet publish "${{ env.API_PROJECT }}" -c Release -o "${{ env.PUBLISH_DIR }}"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.PUBLISH_DIR}}

  deploy:
    runs-on: windows-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_CA89C577336B4D60AD23734EC9D38334 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_241EEA86D9944EB3BF3CB34881793FF0 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_D6040EA2256545EEBB10D481FBF62FB0 }}
          path: app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'ChatApi1'
          slot-name: 'Production'
          package: .
          